// <auto-generated />
using System;
using Ats_Demo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ats_Demo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ats_Demo.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Office")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("09695e55-3381-4a7a-8cc6-5b61cfcaf836"),
                            Age = 30,
                            CreatedDate = new DateTime(2025, 2, 3, 14, 4, 24, 516, DateTimeKind.Local).AddTicks(554),
                            LastModifiedDate = new DateTime(2025, 2, 3, 14, 4, 24, 516, DateTimeKind.Local).AddTicks(555),
                            Name = "John Doe",
                            Office = "New York",
                            Position = "Software Engineer",
                            Salary = 60000m
                        },
                        new
                        {
                            Id = new Guid("bbd89bb9-cad4-47a0-b8dd-8422a745265c"),
                            Age = 35,
                            CreatedDate = new DateTime(2025, 2, 3, 14, 4, 24, 516, DateTimeKind.Local).AddTicks(570),
                            LastModifiedDate = new DateTime(2025, 2, 3, 14, 4, 24, 516, DateTimeKind.Local).AddTicks(571),
                            Name = "Jane Smith",
                            Office = "Los Angeles",
                            Position = "Project Manager",
                            Salary = 75000m
                        },
                        new
                        {
                            Id = new Guid("55bbd9fb-0fb4-4328-97be-c3eccbf9ae49"),
                            Age = 28,
                            CreatedDate = new DateTime(2025, 2, 3, 14, 4, 24, 516, DateTimeKind.Local).AddTicks(578),
                            LastModifiedDate = new DateTime(2025, 2, 3, 14, 4, 24, 516, DateTimeKind.Local).AddTicks(579),
                            Name = "Michael Johnson",
                            Office = "San Francisco",
                            Position = "UI/UX Designer",
                            Salary = 55000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
